version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly", day: "monday" }
    target-branch: "dev"
    commit-message:
      prefix: "build(deps)"
    open-pull-requests-limit: 10

  - package-ecosystem: "pip"
    directory: "/"
    schedule: { interval: "weekly", day: "monday" }
    target-branch: "dev"
    commit-message:
      prefix: "build(deps)"
    open-pull-requests-limit: 10

    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]

