name: CI

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - run: python3 -m pip install -U pip
      - run: pip install -e ".[dev]"
      - run: pre-commit run --all-files

tests:
  name: tests
  runs-on: ubuntu-latest
  needs: lint
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"
    - run: python3 -m pip install -U pip
    - run: pip install -e ".[dev]"
    - run: pytest -q

